[package]
name = "conetty"
version = "0.1.0"
authors = ["Xudong Huang <huangxu008@hotmail.com>"]
license = "MIT"
documentation = "https://docs.rs/conetty"
homepage = "https://github.com/Xudong-Huang/conetty"
repository = "https://github.com/Xudong-Huang/conetty"
keywords = ["protocol", "server", "client"]
readme = "README.md"
description = "An general client server framework for Rust based on coroutine."

[lib]
# crate-type = ["dylib"]

[dependencies]
log = "0.3"
byteorder = "1.0"
may = { git = "ssh://git@gitlab.com/Xudong-Huang/may.git" }
co_waiter = { git = "ssh://git@gitlab.com/Xudong-Huang/co-waiter.git" }
comanaged =  { git = "ssh://git@gitlab.com/Xudong-Huang/comanaged.git" }

[dev-dependencies]
serde = "0.9"
bincode = "1.0.0-alpha7"
token_id = { git = "https://github.com/Xudong-Huang/token_id.git" }
env_logger = "0.4"
serde_derive = "0.9"

[profile.release]
opt-level=3
